package com.xc.touchbox.model.view;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.springframework.beans.BeanUtils;

import com.xc.touchbox.model.Admin;
import com.xc.touchbox.model.User;

/**
 * Account generated by hbm2java
 */
public class AccountView implements java.io.Serializable {

	private Long userId;
	private String username;
	private String email;
	private String mobile;
	private String mobileTelecomOp;
	private Date createTime;
	private Date updateTime;
	private boolean mobileValidated;
	private boolean emailValidated;
	private AdminView admin;
	private UserView user;

	public AccountView() {
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMobileTelecomOp() {
		return this.mobileTelecomOp;
	}

	public void setMobileTelecomOp(String mobileTelecomOp) {
		this.mobileTelecomOp = mobileTelecomOp;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public boolean isMobileValidated() {
		return this.mobileValidated;
	}

	public void setMobileValidated(boolean mobileValidated) {
		this.mobileValidated = mobileValidated;
	}

	public boolean isEmailValidated() {
		return this.emailValidated;
	}

	public void setEmailValidated(boolean emailValidated) {
		this.emailValidated = emailValidated;
	}

	public AdminView getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		if (admin != null) {
			this.admin = new AdminView();
			BeanUtils.copyProperties(admin, this.admin);
		}
	}

	public UserView getUser() {
		return this.user;
	}

	public void setUser(User user) {
		if (user != null) {
			this.user = new UserView();
			BeanUtils.copyProperties(user, this.user);
		}
	}

}
