package com.xc.touchbox.model.view;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.struts2.json.annotations.JSON;
import org.springframework.beans.BeanUtils;

import com.xc.touchbox.model.Product;

/**
 * Classroom generated by hbm2java
 */
public class ClassroomView implements java.io.Serializable {

	private Long classroomId;
	private long productId;
	private String adminName;
	private int periodNum;
	private String name;
	private String imageUrl;
	private String description;
	private String videoUrl;
	private String videoSmallImage;
	private String videoImage;
	private boolean free;
	private int status;
	private Date createTime;
	private Date updateTime;

	private ProductView product;
	
	public ClassroomView() {
	}

	public Long getClassroomId() {
		return classroomId;
	}

	public void setClassroomId(Long classroomId) {
		this.classroomId = classroomId;
	}

	public long getProductId() {
		return productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getAdminName() {
		return adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public int getPeriodNum() {
		return periodNum;
	}

	public void setPeriodNum(int periodNum) {
		this.periodNum = periodNum;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getVideoUrl() {
		return videoUrl;
	}

	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}

	public String getVideoSmallImage() {
		return videoSmallImage;
	}

	public void setVideoSmallImage(String videoSmallImage) {
		this.videoSmallImage = videoSmallImage;
	}

	public String getVideoImage() {
		return videoImage;
	}

	public void setVideoImage(String videoImage) {
		this.videoImage = videoImage;
	}

	public boolean isFree() {
		return free;
	}

	public void setFree(boolean free) {
		this.free = free;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@JSON(format = "yyyy-MM-dd HH:mm:ss")
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public ProductView getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		if(product!=null){
			this.product = new ProductView();
			BeanUtils.copyProperties(product, this.product);
		}
	}

	
}
