package com.xc.touchbox.model.view;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.struts2.json.annotations.JSON;

/**
 * Role generated by hbm2java
 */
public class RoleView implements java.io.Serializable {

	private Integer roleId;
	private int type;
	private int groupId;
	private String name;
	private String memo;
	private int status;
	private Date createTime;

	public RoleView() {
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getGroupId() {
		return groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@JSON(format = "yyyy-MM-dd HH:mm:ss")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getTypeName() {
		return this.type == 2 ? "外部合作" : "内部";
	}

	public String getGroupName() {
		String name = "不限";
		switch(this.groupId){
			case 1:name="超级管理员";
			break;
			case 2:name="销售员";
			break;
			case 3:name="客服";
			break;		
		}
		return name;
	}
}
