package com.xc.touchbox.model.view;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

/**
 * UploadView generated by hbm2java
 */
public class UploadView implements java.io.Serializable {

	private String type;// image-图片，video-视频
	private String filePath;// 文件存放相对路径
	private String sourceFileName;
	private String resourceDirUrl;// 资源目录http地址

	public UploadView() {
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getResourceDirUrl() {
		return resourceDirUrl;
	}

	public void setResourceDirUrl(String resourceDirUrl) {
		this.resourceDirUrl = resourceDirUrl;
	}

	public String getSourceFileName() {
		return sourceFileName;
	}

	public void setSourceFileName(String sourceFileName) {
		this.sourceFileName = sourceFileName;
	}

}
