package com.xc.touchbox.model.view;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.apache.struts2.json.annotations.JSON;

import com.xc.touchbox.model.UserChildren;

/**
 * User generated by hbm2java
 */
public class UserView implements java.io.Serializable {

	private long userId;
	private String username;
	private String email;
	private String mobile;
	private String name;
	private Byte sex;
	private Date birthday;
	private String address;
	private Date createTime;
	private Date loginTime;
	private String loginIp;
	private Date logoutTime;
	private Long longitude;
	private Long latitude;
	private Date placeTime;
	private String portraitUrl;
	private int portraitKey;
	private int status;
	private String signature;
	private Integer integral;
	private Date updateTime;
	private boolean freeze;
	private String freezeDetail;
	private int loginFrequency;
	private int source;
	private int vipLevel;
	
	private List<UserChildren> childrens = new ArrayList<UserChildren>();// 非持久化
	
	public UserView() {
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	@JSON(format = "yyyy-MM-dd")
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@JSON(format = "yyyy-MM-dd HH:mm:ss")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	public Long getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Long longitude) {
		this.longitude = longitude;
	}

	public Long getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Long latitude) {
		this.latitude = latitude;
	}

	public Date getPlaceTime() {
		return this.placeTime;
	}

	public void setPlaceTime(Date placeTime) {
		this.placeTime = placeTime;
	}

	public String getPortraitUrl() {
		return this.portraitUrl;
	}

	public void setPortraitUrl(String portraitUrl) {
		this.portraitUrl = portraitUrl;
	}

	public int getPortraitKey() {
		return this.portraitKey;
	}

	public void setPortraitKey(int portraitKey) {
		this.portraitKey = portraitKey;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public Integer getIntegral() {
		return this.integral;
	}

	public void setIntegral(Integer integral) {
		this.integral = integral;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public boolean isFreeze() {
		return this.freeze;
	}

	public void setFreeze(boolean freeze) {
		this.freeze = freeze;
	}

	public String getFreezeDetail() {
		return this.freezeDetail;
	}

	public void setFreezeDetail(String freezeDetail) {
		this.freezeDetail = freezeDetail;
	}

	public int getLoginFrequency() {
		return this.loginFrequency;
	}

	public void setLoginFrequency(int loginFrequency) {
		this.loginFrequency = loginFrequency;
	}

	public int getSource() {
		return this.source;
	}

	public void setSource(int source) {
		this.source = source;
	}

	public int getVipLevel() {
		return this.vipLevel;
	}

	public void setVipLevel(int vipLevel) {
		this.vipLevel = vipLevel;
	}

	public List<UserChildren> getChildrens() {
		return childrens;
	}

	public void setChildrens(List<UserChildren> childrens) {
		this.childrens = childrens;
	}
}
