package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private Long userId;
	private String username;
	private String password;
	private String email;
	private String mobile;
	private String mobileTelecomOp;
	private Date createTime;
	private Date updateTime;
	private boolean mobileValidated;
	private boolean emailValidated;
	private boolean adminEnabled;// 管理员账号生效的
	private boolean userEnabled;// 用户账号生效的
	private Admin admin;
	private User user;
	private Set complaintReplies = new HashSet(0);

	public Account() {
	}

	public Account(boolean mobileValidated, boolean emailValidated) {
		this.mobileValidated = mobileValidated;
		this.emailValidated = emailValidated;
	}

	public Account(String username, String password, String email,
			String mobile, String mobileTelecomOp, Date createTime,
			Date updateTime, boolean mobileValidated, boolean emailValidated,
			Admin admin, User user, Set complaintReplies) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.mobile = mobile;
		this.mobileTelecomOp = mobileTelecomOp;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.mobileValidated = mobileValidated;
		this.emailValidated = emailValidated;
		this.admin = admin;
		this.user = user;
		this.complaintReplies = complaintReplies;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getMobileTelecomOp() {
		return this.mobileTelecomOp;
	}

	public void setMobileTelecomOp(String mobileTelecomOp) {
		this.mobileTelecomOp = mobileTelecomOp;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public boolean isMobileValidated() {
		return this.mobileValidated;
	}

	public void setMobileValidated(boolean mobileValidated) {
		this.mobileValidated = mobileValidated;
	}

	public boolean isEmailValidated() {
		return this.emailValidated;
	}

	public void setEmailValidated(boolean emailValidated) {
		this.emailValidated = emailValidated;
	}

	public boolean isAdminEnabled() {
		return adminEnabled;
	}

	public void setAdminEnabled(boolean adminEnabled) {
		this.adminEnabled = adminEnabled;
	}

	public boolean isUserEnabled() {
		return userEnabled;
	}

	public void setUserEnabled(boolean userEnabled) {
		this.userEnabled = userEnabled;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set getComplaintReplies() {
		return this.complaintReplies;
	}

	public void setComplaintReplies(Set complaintReplies) {
		this.complaintReplies = complaintReplies;
	}

}
