package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdminRoleRelation generated by hbm2java
 */
public class AdminRoleRelation implements java.io.Serializable {

	private Long relationId;
	private long userId;
	private int roleId;
	private Date createTime;

	private Admin admin;
	private Role role;

	public AdminRoleRelation() {
	}

	public AdminRoleRelation(Admin admin, Role role, Date createTime) {
		this.admin = admin;
		this.role = role;
		this.createTime = createTime;
	}
	
	public AdminRoleRelation(Admin admin, int roleId) {
		this.admin = admin;
		this.roleId = roleId;
	}

	public Long getRelationId() {
		return this.relationId;
	}

	public void setRelationId(Long relationId) {
		this.relationId = relationId;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public int getRoleId() {
		return roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

}
