package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdminMessage generated by hbm2java
 */
public class AdminMessage implements java.io.Serializable {

	private Long id;
	private NotificationMessage notificationMessage;
	private Admin admin;
	private byte status;
	private Date createTime;
	private Date updateTime;

	public AdminMessage() {
	}

	public AdminMessage(byte status) {
		this.status = status;
	}

	public AdminMessage(NotificationMessage notificationMessage, Admin admin,
			byte status, Date createTime, Date updateTime) {
		this.notificationMessage = notificationMessage;
		this.admin = admin;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public NotificationMessage getNotificationMessage() {
		return this.notificationMessage;
	}

	public void setNotificationMessage(NotificationMessage notificationMessage) {
		this.notificationMessage = notificationMessage;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
