package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin extends UserCommon implements java.io.Serializable {

	private int type = 1;
	private String identityCard;
	private String area;
	private String phone;
	private String address;
	private Float salesCut;
	private boolean greenway = true;
	private Long creator;
	private Long parentUserId;
	private Date logoutTime;
	private boolean authorityAvailable;
	private int status;
	private String memo;

	private Set complaints = new HashSet(0);
	private Set lessonPlans = new HashSet(0);
	private Set salesCodes = new HashSet(0);
	private Set adminMessages = new HashSet(0);
	private Set products = new HashSet(0);
	private Set feedbacks = new HashSet(0);
	private Set adminRoleRelations = new HashSet(0);
	private Set informations = new HashSet(0);
	private Set salaryAccounts = new HashSet(0);
	private Set refunds = new HashSet(0);

	private List roleList = new ArrayList(0);// 非持久化
	private Map<String,Boolean> funcA = new HashMap<String,Boolean>();// 非持久化,功能权限
	private List<Resource> menuResources = new ArrayList<Resource>(0);// 非持久化，菜单资源

	public Admin() {
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getIdentityCard() {
		return this.identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Float getSalesCut() {
		return this.salesCut;
	}

	public void setSalesCut(Float salesCut) {
		this.salesCut = salesCut;
	}

	public boolean isGreenway() {
		return this.greenway;
	}

	public void setGreenway(boolean greenway) {
		this.greenway = greenway;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Long getParentUserId() {
		return this.parentUserId;
	}

	public void setParentUserId(Long parentUserId) {
		this.parentUserId = parentUserId;
	}

	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	public boolean isAuthorityAvailable() {
		return this.authorityAvailable;
	}

	public void setAuthorityAvailable(boolean authorityAvailable) {
		this.authorityAvailable = authorityAvailable;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set getComplaints() {
		return this.complaints;
	}

	public void setComplaints(Set complaints) {
		this.complaints = complaints;
	}

	public Set getLessonPlans() {
		return this.lessonPlans;
	}

	public void setLessonPlans(Set lessonPlans) {
		this.lessonPlans = lessonPlans;
	}

	public Set getSalesCodes() {
		return this.salesCodes;
	}

	public void setSalesCodes(Set salesCodes) {
		this.salesCodes = salesCodes;
	}

	public Set getAdminMessages() {
		return this.adminMessages;
	}

	public void setAdminMessages(Set adminMessages) {
		this.adminMessages = adminMessages;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	public Set getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set feedbacks) {
		this.feedbacks = feedbacks;
	}

	public Set getAdminRoleRelations() {
		return this.adminRoleRelations;
	}

	public void setAdminRoleRelations(Set adminRoleRelations) {
		this.adminRoleRelations = adminRoleRelations;
	}

	public Set getInformations() {
		return this.informations;
	}

	public void setInformations(Set informations) {
		this.informations = informations;
	}

	public Set getSalaryAccounts() {
		return this.salaryAccounts;
	}

	public void setSalaryAccounts(Set salaryAccounts) {
		this.salaryAccounts = salaryAccounts;
	}

	public Set getRefunds() {
		return this.refunds;
	}

	public void setRefunds(Set refunds) {
		this.refunds = refunds;
	}

	public List getRoleList() {
		return roleList;
	}

	public void setRoleList(List roleList) {
		this.roleList = roleList;
	}

	public Map<String, Boolean> getFuncA() {
		return funcA;
	}

	public void setFuncA(Map<String, Boolean> funcA) {
		this.funcA = funcA;
	}

	public List<Resource> getMenuResources() {
		return menuResources;
	}

	public void setMenuResources(List<Resource> menuResources) {
		this.menuResources = menuResources;
	}
}
