package com.xc.touchbox.model;

// Generated 2015-7-4 14:54:30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private String cityId;
	private String parentId;
	private String name;
	private String fullName;
	private Integer level;
	private String fullFirstSpell;
	private String firstSpell;
	private String spell;
	private Boolean freeze;
	private BigDecimal longitude;
	private BigDecimal latitude;
	private Boolean city;

	private List<City> children = new ArrayList<City>(0);// 非持久化

	public City() {
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getFullFirstSpell() {
		return this.fullFirstSpell;
	}

	public void setFullFirstSpell(String fullFirstSpell) {
		this.fullFirstSpell = fullFirstSpell;
	}

	public String getFirstSpell() {
		return this.firstSpell;
	}

	public void setFirstSpell(String firstSpell) {
		this.firstSpell = firstSpell;
	}

	public String getSpell() {
		return this.spell;
	}

	public void setSpell(String spell) {
		this.spell = spell;
	}

	public Boolean getFreeze() {
		return this.freeze;
	}

	public void setFreeze(Boolean freeze) {
		this.freeze = freeze;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public Boolean getCity() {
		return this.city;
	}

	public void setCity(Boolean city) {
		this.city = city;
	}

	public List<City> getChildren() {
		return children;
	}

	public void setChildren(List<City> children) {
		this.children = children;
	}

}
