package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1


/**
 * Complaint generated by hbm2java
 */
public class Complaint extends FeedbackCommon implements java.io.Serializable {


}
