package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InformationCat generated by hbm2java
 */
public class InformationCat implements java.io.Serializable {

	private Integer catId;
	private byte type;
	private String name;
	private int level;
	private int sequence;
	private int parentCatId;
	private String memo;
	private byte status;
	private Date createTime;
	private Date updateTime;
	private Set informations = new HashSet(0);

	public InformationCat() {
	}

	public InformationCat(byte type, String name, int level, int sequence,
			int parentCatId, byte status) {
		this.type = type;
		this.name = name;
		this.level = level;
		this.sequence = sequence;
		this.parentCatId = parentCatId;
		this.status = status;
	}

	public InformationCat(byte type, String name, int level, int sequence,
			int parentCatId, String memo, byte status, Date createTime,
			Date updateTime, Set informations) {
		this.type = type;
		this.name = name;
		this.level = level;
		this.sequence = sequence;
		this.parentCatId = parentCatId;
		this.memo = memo;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.informations = informations;
	}

	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	public int getParentCatId() {
		return this.parentCatId;
	}

	public void setParentCatId(int parentCatId) {
		this.parentCatId = parentCatId;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set getInformations() {
		return this.informations;
	}

	public void setInformations(Set informations) {
		this.informations = informations;
	}

}
