package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Information generated by hbm2java
 */
public class Information implements java.io.Serializable {

	private Integer id;
	private InformationCat informationCat;
	private Admin admin;
	private String authorName;
	private int type;
	private String title;
	private String titleImageUrl;
	private String content;
	private String attachment;
	private String memo;// 摘要/备注
	private int sequence;
	private int viewNum;
	private int status;
	private Date createTime;
	private Date editTime;
	private Date updateTime;
	private Set notificationMessages = new HashSet(0);

	public Information() {
	}

	public Information(int type, int sequence, int viewNum) {
		this.type = type;
		this.sequence = sequence;
		this.viewNum = viewNum;
	}

	public Information(InformationCat informationCat, Admin admin, int type,
			String title, String content, String attachment, int sequence,
			int viewNum, int status, Date createTime, Date updateTime,
			Set notificationMessages) {
		this.informationCat = informationCat;
		this.admin = admin;
		this.type = type;
		this.title = title;
		this.content = content;
		this.attachment = attachment;
		this.sequence = sequence;
		this.viewNum = viewNum;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.notificationMessages = notificationMessages;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public InformationCat getInformationCat() {
		return this.informationCat;
	}

	public void setInformationCat(InformationCat informationCat) {
		this.informationCat = informationCat;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
		if (admin != null) {
			setAuthorName(admin.getName());
		}
	}

	public String getAuthorName() {
		return authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitleImageUrl() {
		return titleImageUrl;
	}

	public void setTitleImageUrl(String titleImageUrl) {
		this.titleImageUrl = titleImageUrl;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	public int getViewNum() {
		return this.viewNum;
	}

	public void setViewNum(int viewNum) {
		this.viewNum = viewNum;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getEditTime() {
		return editTime;
	}

	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set getNotificationMessages() {
		return this.notificationMessages;
	}

	public void setNotificationMessages(Set notificationMessages) {
		this.notificationMessages = notificationMessages;
	}

}
