package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NotificationMessage generated by hbm2java
 */
public class NotificationMessage implements java.io.Serializable {

	private Long messageId;
	private Information information;
	private String title;
	private String content;
	private String link;
	private short sequence;
	private byte status;
	private Date createTime;
	private Date updateTime;
	private Set adminMessages = new HashSet(0);
	private Set userMessages = new HashSet(0);

	public NotificationMessage() {
	}

	public NotificationMessage(short sequence, byte status) {
		this.sequence = sequence;
		this.status = status;
	}

	public NotificationMessage(Information information, String title,
			String content, String link, short sequence, byte status,
			Date createTime, Date updateTime, Set adminMessages,
			Set userMessages) {
		this.information = information;
		this.title = title;
		this.content = content;
		this.link = link;
		this.sequence = sequence;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.adminMessages = adminMessages;
		this.userMessages = userMessages;
	}

	public Long getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Long messageId) {
		this.messageId = messageId;
	}

	public Information getInformation() {
		return this.information;
	}

	public void setInformation(Information information) {
		this.information = information;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public short getSequence() {
		return this.sequence;
	}

	public void setSequence(short sequence) {
		this.sequence = sequence;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set getAdminMessages() {
		return this.adminMessages;
	}

	public void setAdminMessages(Set adminMessages) {
		this.adminMessages = adminMessages;
	}

	public Set getUserMessages() {
		return this.userMessages;
	}

	public void setUserMessages(Set userMessages) {
		this.userMessages = userMessages;
	}

}
