package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ProductCat generated by hbm2java
 */
public class ProductCat implements java.io.Serializable {

	private Integer productCatId;
	private String name;
	private Integer suitableStartAge;
	private Integer suitableEndAge;
	private String memo;
	private int status;
	private Date createTime;
	private Date updateTime;

	public Integer getProductCatId() {
		return productCatId;
	}

	public void setProductCatId(Integer productCatId) {
		this.productCatId = productCatId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSuitableStartAge() {
		return suitableStartAge;
	}

	public void setSuitableStartAge(Integer suitableStartAge) {
		this.suitableStartAge = suitableStartAge;
	}

	public Integer getSuitableEndAge() {
		return suitableEndAge;
	}

	public void setSuitableEndAge(Integer suitableEndAge) {
		this.suitableEndAge = suitableEndAge;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
