package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import net.sf.json.JSONArray;

import org.apache.commons.lang3.ArrayUtils;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Long productId;
	private Admin admin;
	private String adminName;
	private int productCatId;
	private String period;
	private String name;
	private String description;
	private float originalPrice;
	private float price;
	private String titleImageUrl;
	private String bannerImageUrl;
	private String imageUrl;
	private String deliveryWarehouse;
	private Date startTime;
	private int giftClassroomPeriodNum;
	private boolean discountExisted = true;
	private int status;
	private Date createTime;
	private Date updateTime;
	private Set productImages = new HashSet(0);
	private Set userOrders = new HashSet(0);

	private List<Goods> goodsList = new ArrayList<Goods>();

	public Product() {
	}

	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
		if (admin != null) {
			this.setAdminName(admin.getName());
		}
	}

	public String getAdminName() {
		return adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public int getProductCatId() {
		return productCatId;
	}

	public void setProductCatId(int productCatId) {
		this.productCatId = productCatId;
	}

	public String getPeriod() {
		return period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public void setPeriods(String[] period) {
		if (ArrayUtils.isNotEmpty(period)) {
			this.setPeriod(JSONArray.fromObject(period).toString());
		}
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public float getOriginalPrice() {
		return originalPrice;
	}

	public void setOriginalPrice(float originalPrice) {
		this.originalPrice = originalPrice;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getTitleImageUrl() {
		return titleImageUrl;
	}

	public void setTitleImageUrl(String titleImageUrl) {
		this.titleImageUrl = titleImageUrl;
	}

	public String getBannerImageUrl() {
		return bannerImageUrl;
	}

	public void setBannerImageUrl(String bannerImageUrl) {
		this.bannerImageUrl = bannerImageUrl;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getDeliveryWarehouse() {
		return deliveryWarehouse;
	}

	public void setDeliveryWarehouse(String deliveryWarehouse) {
		this.deliveryWarehouse = deliveryWarehouse;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public boolean isDiscountExisted() {
		return this.discountExisted;
	}

	public void setDiscountExisted(boolean discountExisted) {
		this.discountExisted = discountExisted;
	}

	public int getGiftClassroomPeriodNum() {
		return giftClassroomPeriodNum;
	}

	public void setGiftClassroomPeriodNum(int giftClassroomPeriodNum) {
		this.giftClassroomPeriodNum = giftClassroomPeriodNum;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set getProductImages() {
		return this.productImages;
	}

	public void setProductImages(Set productImages) {
		this.productImages = productImages;
	}

	public Set getUserOrders() {
		return this.userOrders;
	}

	public void setUserOrders(Set userOrders) {
		this.userOrders = userOrders;
	}

	public List<Goods> getGoodsList() {
		return goodsList;
	}

	public void setGoodsList(List<Goods> goodsList) {
		this.goodsList = goodsList;
	}

}
