package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Refund generated by hbm2java
 */
public class Refund implements java.io.Serializable {

	private Integer refundId;
	private Admin admin;
	private UserOrder userOrder;
	private User user;
	private String refundReason;
	private Byte refundWay;
	private String userContactWay;
	private Long approvalAdminId;
	private Integer refundFee;
	private String memo;
	private byte status;
	private Date createTime;
	private Date updateTime;
	private Date refundTime;

	public Refund() {
	}

	public Refund(byte status) {
		this.status = status;
	}

	public Refund(Admin admin, UserOrder userOrder, User user,
			String refundReason, Byte refundWay, String userContactWay,
			Long approvalAdminId, Integer refundFee, String memo, byte status,
			Date createTime, Date updateTime, Date refundTime) {
		this.admin = admin;
		this.userOrder = userOrder;
		this.user = user;
		this.refundReason = refundReason;
		this.refundWay = refundWay;
		this.userContactWay = userContactWay;
		this.approvalAdminId = approvalAdminId;
		this.refundFee = refundFee;
		this.memo = memo;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.refundTime = refundTime;
	}

	public Integer getRefundId() {
		return this.refundId;
	}

	public void setRefundId(Integer refundId) {
		this.refundId = refundId;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public UserOrder getUserOrder() {
		return this.userOrder;
	}

	public void setUserOrder(UserOrder userOrder) {
		this.userOrder = userOrder;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getRefundReason() {
		return this.refundReason;
	}

	public void setRefundReason(String refundReason) {
		this.refundReason = refundReason;
	}

	public Byte getRefundWay() {
		return this.refundWay;
	}

	public void setRefundWay(Byte refundWay) {
		this.refundWay = refundWay;
	}

	public String getUserContactWay() {
		return this.userContactWay;
	}

	public void setUserContactWay(String userContactWay) {
		this.userContactWay = userContactWay;
	}

	public Long getApprovalAdminId() {
		return this.approvalAdminId;
	}

	public void setApprovalAdminId(Long approvalAdminId) {
		this.approvalAdminId = approvalAdminId;
	}

	public Integer getRefundFee() {
		return this.refundFee;
	}

	public void setRefundFee(Integer refundFee) {
		this.refundFee = refundFee;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Date getRefundTime() {
		return this.refundTime;
	}

	public void setRefundTime(Date refundTime) {
		this.refundTime = refundTime;
	}

}
