package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RoleMenuAuthority generated by hbm2java
 */
public class RoleResourceAuthority implements java.io.Serializable {

	private Integer relationId;
	private Role role;
	private Resource resource;
	private Date createTime;

	public RoleResourceAuthority() {
	}

	public RoleResourceAuthority(Role role, Resource resource, Date createTime) {
		this.role = role;
		this.resource = resource;
		this.createTime = createTime;
	}

	public Integer getRelationId() {
		return this.relationId;
	}

	public void setRelationId(Integer relationId) {
		this.relationId = relationId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
