package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SalesCode generated by hbm2java
 */
public class SalesCode implements java.io.Serializable {

	private String salesCode;
	private Admin admin;
	private User user;
	private byte status;
	private Date createTime;
	private Date updateTime;

	public SalesCode() {
	}

	public SalesCode(String salesCode, byte status) {
		this.salesCode = salesCode;
		this.status = status;
	}

	public SalesCode(String salesCode, Admin admin, User user, byte status,
			Date createTime, Date updateTime) {
		this.salesCode = salesCode;
		this.admin = admin;
		this.user = user;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public String getSalesCode() {
		return this.salesCode;
	}

	public void setSalesCode(String salesCode) {
		this.salesCode = salesCode;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
