package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;

import com.xc.touchbox.dao.CDAOTemplate;

/**
 * Serial generated by hbm2java
 */
public class Serial implements java.io.Serializable {

	private String serialId;
	private String version;
	private User user;
	private String channel;
	private String platform;
	private Integer softType;
	private String deviceId;
	private Date createTime;
	private Date updateTime;
	private Byte status;
	private String imei;
	private boolean pushEnabled;
	private Set verifications = new HashSet(0);

	public Serial() {
	}

	public Serial(String serialId, boolean pushEnabled) {
		this.serialId = serialId;
		this.pushEnabled = pushEnabled;
	}

	public Serial(String serialId, User user, String channel, String platform,
			Integer softType, String deviceId, Date createTime,
			Date updateTime, Byte status, String imei, boolean pushEnabled,
			Set verifications) {
		this.serialId = serialId;
		this.user = user;
		this.channel = channel;
		this.platform = platform;
		this.softType = softType;
		this.deviceId = deviceId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.status = status;
		this.imei = imei;
		this.pushEnabled = pushEnabled;
		this.verifications = verifications;
	}

	public String getSerialId() {
		return this.serialId;
	}

	public void setSerialId(String serialId) {
		this.serialId = serialId;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public Integer getSoftType() {
		return this.softType;
	}

	public void setSoftType(Integer softType) {
		this.softType = softType;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public boolean isPushEnabled() {
		return this.pushEnabled;
	}

	public void setPushEnabled(boolean pushEnabled) {
		this.pushEnabled = pushEnabled;
	}

	public Set getVerifications() {
		return this.verifications;
	}

	public void setVerifications(Set verifications) {
		this.verifications = verifications;
	}

	/**
	 * 是否App平台
	 * 
	 * @return
	 */
	public boolean isAppPlatform() {
		return StringUtils.isNotEmpty(platform)
				&& (CDAOTemplate.CONSTANT_PLATFORM_ANDROID
						.equalsIgnoreCase(platform) || CDAOTemplate.CONSTANT_PLATFORM_IPHONE
						.equalsIgnoreCase(platform));
	}

}
