package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserCommon generated by hbm2java
 */
public class UserCommon implements java.io.Serializable {

	private long userId;
	private Account account;
	private String name;
	private String username;
	private String email;
	private String mobile;
	private Byte sex = 0;
	private Date birthday;
	private String address;
	private Date createTime;
	private Date updateTime;
	private Date loginTime;
	private String loginIp;

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Byte getSex() {
		return sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	public String getSexName() {
		if (sex == null) {
			return "-";
		} else if (sex == 1) {
			return "男";
		} else {
			return "女";
		}
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Date getLoginTime() {
		return loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public String getLoginIp() {
		return loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	/**
	 * 账号数据是否变化
	 * 
	 * @param dbObj
	 * @return
	 */
	public boolean isAccountChanged(UserCommon dbObj) {
		boolean result = (dbObj.getMobile() != null && this.getMobile() != null && dbObj
				.getMobile().equalsIgnoreCase(this.getMobile()));
		result = result
				&& (dbObj.getEmail() != null && this.getEmail() != null && dbObj
						.getEmail().equalsIgnoreCase(this.getEmail()));

		return !result;
	}

}
