package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserDelivery generated by hbm2java
 */
public class UserDelivery implements java.io.Serializable {

	private Long id;
	private long orderId;
	private long userId;
	private String company;
	private String wareHouse;
	private String shipmentId;
	private String shipmentType;
	private String carrier;
	private String name;
	private String mobile;
	private String state;
	private String city;
	private String address;
	private String goodsId;
	private String itemName;
	private int itemCount = 1;
	private String responseInfo;
	private int status;
	private Date createTime;
	private Date updateTime;
	private Date cancelTime;
	private Date closeTime;

	public UserDelivery() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getOrderId() {
		return orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getWareHouse() {
		return wareHouse;
	}

	public void setWareHouse(String wareHouse) {
		this.wareHouse = wareHouse;
	}

	public String getShipmentId() {
		return shipmentId;
	}

	public void setShipmentId(String shipmentId) {
		this.shipmentId = shipmentId;
	}

	public String getShipmentType() {
		return shipmentType;
	}

	public void setShipmentType(String shipmentType) {
		this.shipmentType = shipmentType;
	}

	public String getCarrier() {
		return carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * 解析地址并生成省市信息
	 */
	public void parseAddress() {
		if (address != null) {
			int offset = address.indexOf("省"), offset1 = -1;
			if (offset >= 2 && offset <= 4) {
				setState(address.substring(0, offset + 1));
			} else {
				offset = address.indexOf("自治区");
				if (offset >= 3 && offset <= 5) {
					setState(address.substring(0, offset + 3));
				} else {
					offset = address.indexOf("市");// 直辖市
					if (offset == 2) {
						String city = address.substring(0, offset + 1);
						setState(city);
						setCity(city);
					}
				}
			}
			if (offset != -1 && getCity() == null) {
				offset1 = address.indexOf("自治州", offset);
				if (offset1 != -1) {
					setCity(address.substring(offset + 1, offset1 + 3));
				}else{
					offset1 = address.indexOf("地区", offset);
					if (offset1 != -1) {
						setCity(address.substring(offset + 1, offset1 + 2));
					}else{
						offset1 = address.indexOf("市", offset);
						if (offset1 != -1) {
							setCity(address.substring(offset + 1, offset1 + 1));
						}
					}
				}
			}

		}
	}

	public String getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public int getItemCount() {
		return itemCount;
	}

	public void setItemCount(int itemCount) {
		this.itemCount = itemCount;
	}

	public String getResponseInfo() {
		return responseInfo;
	}

	public void setResponseInfo(String responseInfo) {
		this.responseInfo = responseInfo;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Date getCancelTime() {
		return cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}

	public Date getCloseTime() {
		return closeTime;
	}

	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	/**
	 * 当前对象转变为出库单数据
	 * 
	 * @param format
	 * @return
	 */
	public String toShipmentRequest(String format) {
		StringBuilder a = new StringBuilder("<ShipmentRequest>");

		a.append("<Company>").append(this.getCompany()).append("</Company>");
		a.append("<WareHouse>").append(this.getWareHouse())
				.append("</WareHouse>");
		a.append("<TotalQty>1</TotalQty><TotalLines>1</TotalLines>");
		a.append("<ShipmentId>").append(this.getShipmentId())
				.append("</ShipmentId>");
		a.append("<ShipmentType>").append(this.getShipmentType())
				.append("</ShipmentType>");
		a.append("<Carrier>").append(this.getCarrier()).append("</Carrier>");
		a.append("<Name>").append(this.getName()).append("</Name>");
		a.append("<Mobile>").append(this.getMobile()).append("</Mobile>");
		a.append("<State>").append(this.getState()).append("</State>");
		a.append("<City>").append(this.getCity()).append("</City>");
		a.append("<Address>").append(this.getAddress()).append("</Address>");
		a.append("<Invoice>N</Invoice>");
		a.append("<Items><Item><Item>").append(this.getGoodsId())
				.append("</Item>");
		a.append("<ItemName>").append(this.getItemName()).append("</ItemName>");
		a.append("<ItemCount>").append(this.getItemCount())
				.append("</ItemCount>");
		a.append("</Item></Items></ShipmentRequest>");

		return a.toString();
	}
}
