package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserMessage generated by hbm2java
 */
public class UserMessage implements java.io.Serializable {

	private Long id;
	private NotificationMessage notificationMessage;
	private User user;
	private byte status;
	private Date createTime;
	private Date updateTime;

	public UserMessage() {
	}

	public UserMessage(byte status) {
		this.status = status;
	}

	public UserMessage(NotificationMessage notificationMessage, User user,
			byte status, Date createTime, Date updateTime) {
		this.notificationMessage = notificationMessage;
		this.user = user;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public NotificationMessage getNotificationMessage() {
		return this.notificationMessage;
	}

	public void setNotificationMessage(NotificationMessage notificationMessage) {
		this.notificationMessage = notificationMessage;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
