package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1


/**
 * UserClassroomCollection generated by hbm2java
 */
public class UserClassroomCollection extends UserClassroom implements
		java.io.Serializable {

}
