package com.xc.touchbox.model;

// Generated 2015-5-23 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Verification generated by hbm2java
 */
public class Verification implements java.io.Serializable {

	private long verificationId;
	private Serial serial;
	private String code;
	private String mobile;
	private Date createTime;
	private Byte status;
	private Date updateTime;

	public Verification() {
	}

	public Verification(long verificationId, Serial serial) {
		this.verificationId = verificationId;
		this.serial = serial;
	}

	public Verification(long verificationId, Serial serial, String code,
			String mobile, Date createTime, Byte status, Date updateTime) {
		this.verificationId = verificationId;
		this.serial = serial;
		this.code = code;
		this.mobile = mobile;
		this.createTime = createTime;
		this.status = status;
		this.updateTime = updateTime;
	}

	public long getVerificationId() {
		return this.verificationId;
	}

	public void setVerificationId(long verificationId) {
		this.verificationId = verificationId;
	}

	public Serial getSerial() {
		return this.serial;
	}

	public void setSerial(Serial serial) {
		this.serial = serial;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
